### PR TITLE
Add tests for 7-zip/7-zip and 7-zip/7-zip-x64

### PR DESCRIPTION
**Pull request by huiyu-turbo**
I added test scripts and support files for 7-zip/7-zip and 7-zip/7-zip-x64. I also edited the .gitignore and READEME file.

I validated the test scripts by cloning the repo into a clean system and running `executor.bat` for the apps.

We may need to restructure the files.

### CODE REVIEW

**Review by davetagg — APPROVED** [review]

**Review by davetagg — CHANGES_REQUESTED** [review]
I think I would prefer if the "executor.bat" and "test.sikuli" folder were in a "Test" folder under each app folder.
Same for the common test stuff in the _INCLUDE folder, I think it should be in a "Test" subfolder.

**Comment by davetagg** [comment]
> > I think I would prefer if the "executor.bat" and "test.sikuli" folder were in a "Test" folder under each app folder. Same for the common test stuff in the _INCLUDE folder, I think it should be in a "Test" subfolder.
> 
> In that case, do we need to also create a subfolder for build related files?

It's probably not a bad idea.  Might take some minor adjustments to the scripts.  I'll take a look at that when I'm back.

**Comment by huiyu-turbo** [comment]
I moved test related files inside "Test" folder.

**Comment by huiyu-turbo** [comment]
The test scripts have been moved to another project: https://github.com/turboapps/powershell-tests.

**Pull request closed without merging**
